IF OBJECT_ID('dbo.AsciiCode') IS NOT NULL
BEGIN
	DROP TABLE dbo.AsciiCode
END

GO

CREATE TABLE [dbo].[AsciiCode] (
	[DecimalCode] [INT] NOT NULL
	,[OctalCode] [INT] NOT NULL
	,[HexidecimalCode] [VARCHAR](50) NOT NULL
	,[BinaryCode] [INT] NULL
	,[Symbol] [VARCHAR](50) NULL
	,[HtmlNumber] [VARCHAR](50) NULL
	,[HtmlName] [VARCHAR](50) NULL
	,[CodeDescription] [VARCHAR](75) NULL
	,[CharacterGroup] [VARCHAR](50) NULL
	,[CaretNotation] [VARCHAR](5) NULL
	,[CharacterEscapeCode] [VARCHAR](5) NULL
	,CONSTRAINT [PK_AsciiCode_DecimalCode] PRIMARY KEY CLUSTERED
	(
	[DecimalCode] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]

GO

EXEC sys.sp_addextendedproperty	@name = N'MS_Description'
								,@value = N'Computers can only understand numbers, so an ASCII code is the numerical representation of a character. 
 
Using the DecimalCode column, character codes 0-31 in the table are unprintable control codes and are used to control peripherals such as printers. 
 
Character codes 32-127 are common for all the different variations of the ASCII table. They are called printable characters and represent letters, digits, punctuation marks, and a few miscellaneous symbols. You will find almost every character on your keyboard. Character 127 represents the command DEL.
 
The extended ASCII codes are character codes 128-255 (ISO 8859-1). Codes 129-159 contain the Microsoft Windows Latin-1 extended characters.'
								,@level0type = N'SCHEMA'
								,@level0name = N'dbo'
								,@level1type = N'TABLE'
								,@level1name = N'AsciiCode'
								,@level2type = N'COLUMN'
								,@level2name = N'DecimalCode'
GO

INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (0, 0, '0', 0, 'NUL', '&#000;', '', 'Null char', 'Control character', '^@', '\0')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (1, 1, '1', 1, 'SOH', '&#001;', '', 'Start of Heading', 'Control character', '^A', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (2, 2, '2', 10, 'STX', '&#002;', '', 'Start of Text', 'Control character', '^B', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (3, 3, '3', 11, 'ETX', '&#003;', '', 'End of Text', 'Control character', '^C', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (4, 4, '4', 100, 'EOT', '&#004;', '', 'End of Transmission', 'Control character', '^D', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (5, 5, '5', 101, 'ENQ', '&#005;', '', 'Enquiry', 'Control character', '^E', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (6, 6, '6', 110, 'ACK', '&#006;', '', 'Acknowledgment', 'Control character', '^F', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (7, 7, '7', 111, 'BEL', '&#007;', '', 'Bell', 'Control character', '^G', '\a')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (8, 10, '8', 1000, 'BS', '&#008;', '', 'Back Space', 'Control character', '^H', '\b')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (9, 11, '9', 1001, 'HT', '&#009;', '', 'Horizontal Tab', 'Control character', '^I', '\t')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (10, 12, '0A', 1010, 'LF', '&#010;', '', 'Line Feed', 'Control character', '^J', '\n')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (11, 13, '0B', 1011, 'VT', '&#011;', '', 'Vertical Tab', 'Control character', '^K', '\v')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (12, 14, '0C', 1100, 'FF', '&#012;', '', 'Form Feed', 'Control character', '^L', '\f')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (13, 15, '0D', 1101, 'CR', '&#013;', '', 'Carriage Return', 'Control character', '^M', '\r')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (14, 16, '0E', 1110, 'SO', '&#014;', '', 'Shift Out / X-On', 'Control character', '^N', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (15, 17, '0F', 1111, 'SI', '&#015;', '', 'Shift In / X-Off', 'Control character', '^O', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (16, 20, '10', 10000, 'DLE', '&#016;', '', 'Data Line Escape', 'Control character', '^P', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (17, 21, '11', 10001, 'DC1', '&#017;', '', 'Device Control 1 (oft. XON)', 'Control character', '^Q', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (18, 22, '12', 10010, 'DC2', '&#018;', '', 'Device Control 2', 'Control character', '^R', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (19, 23, '13', 10011, 'DC3', '&#019;', '', 'Device Control 3 (oft. XOFF)', 'Control character', '^S', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (20, 24, '14', 10100, 'DC4', '&#020;', '', 'Device Control 4', 'Control character', '^T', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (21, 25, '15', 10101, 'NAK', '&#021;', '', 'Negative Acknowledgement', 'Control character', '^U', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (22, 26, '16', 10110, 'SYN', '&#022;', '', 'Synchronous Idle', 'Control character', '^V', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (23, 27, '17', 10111, 'ETB', '&#023;', '', 'End of Transmit Block', 'Control character', '^W', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (24, 30, '18', 11000, 'CAN', '&#024;', '', 'Cancel', 'Control character', '^X', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (25, 31, '19', 11001, 'EM', '&#025;', '', 'End of Medium', 'Control character', '^Y', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (26, 32, '1A', 11010, 'SUB', '&#026;', '', 'Substitute', 'Control character', '^Z', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (27, 33, '1B', 11011, 'ESC', '&#027;', '', 'Escape', 'Control character', '^[', '\e')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (28, 34, '1C', 11100, 'FS', '&#028;', '', 'File Separator', 'Control character', '^\', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (29, 35, '1D', 11101, 'GS', '&#029;', '', 'Group Separator', 'Control character', '^]', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (30, 36, '1E', 11110, 'RS', '&#030;', '', 'Record Separator', 'Control character', '^^', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (31, 37, '1F', 11111, 'US', '&#031;', '', 'Unit Separator', 'Control character', '^_', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (32, 40, '20', 100000, '', '&#32;', '', 'Space', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (33, 41, '21', 100001, '!', '&#33;', '', 'Exclamation mark', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (34, 42, '22', 100010, '"', '&#34;', '&quot;', 'Double quotes (or speech marks)', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (35, 43, '23', 100011, '#', '&#35;', '', 'Number', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (36, 44, '24', 100100, '$', '&#36;', '', 'Dollar', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (37, 45, '25', 100101, '%', '&#37;', '', 'Procenttecken', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (38, 46, '26', 100110, '&', '&#38;', '&amp;', 'Ampersand', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (39, 47, '27', 100111, '''', '&#39;', '', 'Single quote', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (40, 50, '28', 101000, '(', '&#40;', '', 'Open parenthesis (or open bracket)', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (41, 51, '29', 101001, ')', '&#41;', '', 'Close parenthesis (or close bracket)', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (42, 52, '2A', 101010, '*', '&#42;', '', 'Asterisk', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (43, 53, '2B', 101011, '+', '&#43;', '', 'Plus', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (44, 54, '2C', 101100, ',', '&#44;', '', 'Comma', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (45, 55, '2D', 101101, '-', '&#45;', '', 'Hyphen', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (46, 56, '2E', 101110, '.', '&#46;', '', 'Period, dot or full stop', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (47, 57, '2F', 101111, '/', '&#47;', '', 'Slash or divide', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (48, 60, '30', 110000, '0', '&#48;', '', 'Zero', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (49, 61, '31', 110001, '1', '&#49;', '', 'One', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (50, 62, '32', 110010, '2', '&#50;', '', 'Two', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (51, 63, '33', 110011, '3', '&#51;', '', 'Three', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (52, 64, '34', 110100, '4', '&#52;', '', 'Four', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (53, 65, '35', 110101, '5', '&#53;', '', 'Five', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (54, 66, '36', 110110, '6', '&#54;', '', 'Six', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (55, 67, '37', 110111, '7', '&#55;', '', 'Seven', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (56, 70, '38', 111000, '8', '&#56;', '', 'Eight', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (57, 71, '39', 111001, '9', '&#57;', '', 'Nine', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (58, 72, '3A', 111010, ':', '&#58;', '', 'Colon', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (59, 73, '3B', 111011, ';', '&#59;', '', 'Semicolon', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (60, 74, '3C', 111100, '<', '&#60;', '&lt;', 'Less than (or open angled bracket)', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (61, 75, '3D', 111101, '=', '&#61;', '', 'Equals', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (62, 76, '3E', 111110, '>', '&#62;', '&gt;', 'Greater than (or close angled bracket)', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (63, 77, '3F', 111111, '?', '&#63;', '', 'Question mark', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (64, 100, '40', 1000000, '@', '&#64;', '', 'At symbol', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (65, 101, '41', 1000001, 'A', '&#65;', '', 'Uppercase A', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (66, 102, '42', 1000010, 'B', '&#66;', '', 'Uppercase B', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (67, 103, '43', 1000011, 'C', '&#67;', '', 'Uppercase C', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (68, 104, '44', 1000100, 'D', '&#68;', '', 'Uppercase D', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (69, 105, '45', 1000101, 'E', '&#69;', '', 'Uppercase E', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (70, 106, '46', 1000110, 'F', '&#70;', '', 'Uppercase F', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (71, 107, '47', 1000111, 'G', '&#71;', '', 'Uppercase G', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (72, 110, '48', 1001000, 'H', '&#72;', '', 'Uppercase H', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (73, 111, '49', 1001001, 'I', '&#73;', '', 'Uppercase I', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (74, 112, '4A', 1001010, 'J', '&#74;', '', 'Uppercase J', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (75, 113, '4B', 1001011, 'K', '&#75;', '', 'Uppercase K', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (76, 114, '4C', 1001100, 'L', '&#76;', '', 'Uppercase L', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (77, 115, '4D', 1001101, 'M', '&#77;', '', 'Uppercase M', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (78, 116, '4E', 1001110, 'N', '&#78;', '', 'Uppercase N', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (79, 117, '4F', 1001111, 'O', '&#79;', '', 'Uppercase O', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (80, 120, '50', 1010000, 'P', '&#80;', '', 'Uppercase P', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (81, 121, '51', 1010001, 'Q', '&#81;', '', 'Uppercase Q', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (82, 122, '52', 1010010, 'R', '&#82;', '', 'Uppercase R', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (83, 123, '53', 1010011, 'S', '&#83;', '', 'Uppercase S', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (84, 124, '54', 1010100, 'T', '&#84;', '', 'Uppercase T', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (85, 125, '55', 1010101, 'U', '&#85;', '', 'Uppercase U', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (86, 126, '56', 1010110, 'V', '&#86;', '', 'Uppercase V', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (87, 127, '57', 1010111, 'W', '&#87;', '', 'Uppercase W', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (88, 130, '58', 1011000, 'X', '&#88;', '', 'Uppercase X', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (89, 131, '59', 1011001, 'Y', '&#89;', '', 'Uppercase Y', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (90, 132, '5A', 1011010, 'Z', '&#90;', '', 'Uppercase Z', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (91, 133, '5B', 1011011, '[', '&#91;', '', 'Opening bracket', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (92, 134, '5C', 1011100, '\', '&#92;', '', 'Backslash', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (93, 135, '5D', 1011101, ']', '&#93;', '', 'Closing bracket', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (94, 136, '5E', 1011110, '^', '&#94;', '', 'Caret - circumflex', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (95, 137, '5F', 1011111, '_', '&#95;', '', 'Underscore', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (96, 140, '60', 1100000, '`', '&#96;', '', 'Grave accent', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (97, 141, '61', 1100001, 'a', '&#97;', '', 'Lowercase a', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (98, 142, '62', 1100010, 'b', '&#98;', '', 'Lowercase b', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (99, 143, '63', 1100011, 'c', '&#99;', '', 'Lowercase c', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (100, 144, '64', 1100100, 'd', '&#100;', '', 'Lowercase d', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (101, 145, '65', 1100101, 'e', '&#101;', '', 'Lowercase e', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (102, 146, '66', 1100110, 'f', '&#102;', '', 'Lowercase f', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (103, 147, '67', 1100111, 'g', '&#103;', '', 'Lowercase g', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (104, 150, '68', 1101000, 'h', '&#104;', '', 'Lowercase h', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (105, 151, '69', 1101001, 'i', '&#105;', '', 'Lowercase i', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (106, 152, '6A', 1101010, 'j', '&#106;', '', 'Lowercase j', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (107, 153, '6B', 1101011, 'k', '&#107;', '', 'Lowercase k', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (108, 154, '6C', 1101100, 'l', '&#108;', '', 'Lowercase l', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (109, 155, '6D', 1101101, 'm', '&#109;', '', 'Lowercase m', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (110, 156, '6E', 1101110, 'n', '&#110;', '', 'Lowercase n', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (111, 157, '6F', 1101111, 'o', '&#111;', '', 'Lowercase o', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (112, 160, '70', 1110000, 'p', '&#112;', '', 'Lowercase p', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (113, 161, '71', 1110001, 'q', '&#113;', '', 'Lowercase q', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (114, 162, '72', 1110010, 'r', '&#114;', '', 'Lowercase r', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (115, 163, '73', 1110011, 's', '&#115;', '', 'Lowercase s', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (116, 164, '74', 1110100, 't', '&#116;', '', 'Lowercase t', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (117, 165, '75', 1110101, 'u', '&#117;', '', 'Lowercase u', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (118, 166, '76', 1110110, 'v', '&#118;', '', 'Lowercase v', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (119, 167, '77', 1110111, 'w', '&#119;', '', 'Lowercase w', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (120, 170, '78', 1111000, 'x', '&#120;', '', 'Lowercase x', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (121, 171, '79', 1111001, 'y', '&#121;', '', 'Lowercase y', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (122, 172, '7A', 1111010, 'z', '&#122;', '', 'Lowercase z', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (123, 173, '7B', 1111011, '{', '&#123;', '', 'Opening brace', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (124, 174, '7C', 1111100, '|', '&#124;', '', 'Vertical bar', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (125, 175, '7D', 1111101, '}', '&#125;', '', 'Closing brace', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (126, 176, '7E', 1111110, '~', '&#126;', '', 'Equivalency sign - tilde', 'Printable character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (127, 177, '7F', 1111111, '', '&#127;', '', 'Delete', 'Extended character', '^?', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (128, 200, '80', 10000000, '€', '&#128;', '&euro;', 'Euro sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (129, 201, '81', 10000001, '', '', '', '', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (130, 202, '82', 10000010, '‚', '&#130;', '&sbquo;', 'Single low-9 quotation mark', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (131, 203, '83', 10000011, 'ƒ', '&#131;', '&fnof;', 'Latin small letter f with hook', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (132, 204, '84', 10000100, '„', '&#132;', '&bdquo;', 'Double low-9 quotation mark', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (133, 205, '85', 10000101, '…', '&#133;', '&hellip;', 'Horizontal ellipsis', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (134, 206, '86', 10000110, '†', '&#134;', '&dagger;', 'Dagger', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (135, 207, '87', 10000111, '‡', '&#135;', '&Dagger;', 'Double dagger', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (136, 210, '88', 10001000, 'ˆ', '&#136;', '&circ;', 'Modifier letter circumflex accent', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (137, 211, '89', 10001001, '‰', '&#137;', '&permil;', 'Per mille sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (138, 212, '8A', 10001010, 'Š', '&#138;', '&Scaron;', 'Latin capital letter S with caron', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (139, 213, '8B', 10001011, '‹', '&#139;', '&lsaquo;', 'Single left-pointing angle quotation', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (140, 214, '8C', 10001100, 'Œ', '&#140;', '&OElig;', 'Latin capital ligature OE', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (141, 215, '8D', 10001101, '', '', '', '', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (142, 216, '8E', 10001110, 'Ž', '&#142;', '', 'Latin captial letter Z with caron', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (143, 217, '8F', 10001111, '', '', '', '', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (144, 220, '90', 10010000, '', '', '', '', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (145, 221, '91', 10010001, '‘', '&#145;', '&lsquo;', 'Left single quotation mark', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (146, 222, '92', 10010010, '’', '&#146;', '&rsquo;', 'Right single quotation mark', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (147, 223, '93', 10010011, '“', '&#147;', '&ldquo;', 'Left double quotation mark', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (148, 224, '94', 10010100, '”', '&#148;', '&rdquo;', 'Right double quotation mark', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (149, 225, '95', 10010101, '•', '&#149;', '&bull;', 'Bullet', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (150, 226, '96', 10010110, '–', '&#150;', '&ndash;', 'En dash', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (151, 227, '97', 10010111, '—', '&#151;', '&mdash;', 'Em dash', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (152, 230, '98', 10011000, '˜', '&#152;', '&tilde;', 'Small tilde', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (153, 231, '99', 10011001, '™', '&#153;', '&trade;', 'Trade mark sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (154, 232, '9A', 10011010, 'š', '&#154;', '&scaron;', 'Latin small letter S with caron', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (155, 233, '9B', 10011011, '›', '&#155;', '&rsaquo;', 'Single right-pointing angle quotation mark', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (156, 234, '9C', 10011100, 'œ', '&#156;', '&oelig;', 'Latin small ligature oe', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (157, 235, '9D', 10011101, '', '', '', '', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (158, 236, '9E', 10011110, 'ž', '&#158;', '', 'Latin small letter z with caron', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (159, 237, '9F', 10011111, 'Ÿ', '&#159;', '&Yuml;', 'Latin capital letter Y with diaeresis', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (160, 240, 'A0', 10100000, '', '&#160;', '&nbsp;', 'Non-breaking space', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (161, 241, 'A1', 10100001, '¡', '&#161;', '&iexcl;', 'Inverted exclamation mark', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (162, 242, 'A2', 10100010, '¢', '&#162;', '&cent;', 'Cent sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (163, 243, 'A3', 10100011, '£', '&#163;', '&pound;', 'Pound sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (164, 244, 'A4', 10100100, '¤', '&#164;', '&curren;', 'Currency sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (165, 245, 'A5', 10100101, '¥', '&#165;', '&yen;', 'Yen sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (166, 246, 'A6', 10100110, '¦', '&#166;', '&brvbar;', 'Pipe, Broken vertical bar', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (167, 247, 'A7', 10100111, '§', '&#167;', '&sect;', 'Section sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (168, 250, 'A8', 10101000, '¨', '&#168;', '&uml;', 'Spacing diaeresis - umlaut', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (169, 251, 'A9', 10101001, '©', '&#169;', '&copy;', 'Copyright sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (170, 252, 'AA', 10101010, 'ª', '&#170;', '&ordf;', 'Feminine ordinal indicator', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (171, 253, 'AB', 10101011, '«', '&#171;', '&laquo;', 'Left double angle quotes', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (172, 254, 'AC', 10101100, '¬', '&#172;', '&not;', 'Not sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (173, 255, 'AD', 10101101, '­', '&#173;', '&shy;', 'Soft hyphen', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (174, 256, 'AE', 10101110, '®', '&#174;', '&reg;', 'Registered trade mark sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (175, 257, 'AF', 10101111, '¯', '&#175;', '&macr;', 'Spacing macron - overline', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (176, 260, 'B0', 10110000, '°', '&#176;', '&deg;', 'Degree sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (177, 261, 'B1', 10110001, '±', '&#177;', '&plusmn;', 'Plus-or-minus sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (178, 262, 'B2', 10110010, '²', '&#178;', '&sup2;', 'Superscript two - squared', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (179, 263, 'B3', 10110011, '³', '&#179;', '&sup3;', 'Superscript three - cubed', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (180, 264, 'B4', 10110100, '´', '&#180;', '&acute;', 'Acute accent - spacing acute', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (181, 265, 'B5', 10110101, 'µ', '&#181;', '&micro;', 'Micro sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (182, 266, 'B6', 10110110, '¶', '&#182;', '&para;', 'Pilcrow sign - paragraph sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (183, 267, 'B7', 10110111, '·', '&#183;', '&middot;', 'Middle dot - Georgian comma', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (184, 270, 'B8', 10111000, '¸', '&#184;', '&cedil;', 'Spacing cedilla', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (185, 271, 'B9', 10111001, '¹', '&#185;', '&sup1;', 'Superscript one', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (186, 272, 'BA', 10111010, 'º', '&#186;', '&ordm;', 'Masculine ordinal indicator', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (187, 273, 'BB', 10111011, '»', '&#187;', '&raquo;', 'Right double angle quotes', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (188, 274, 'BC', 10111100, '¼', '&#188;', '&frac14;', 'Fraction one quarter', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (189, 275, 'BD', 10111101, '½', '&#189;', '&frac12;', 'Fraction one half', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (190, 276, 'BE', 10111110, '¾', '&#190;', '&frac34;', 'Fraction three quarters', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (191, 277, 'BF', 10111111, '¿', '&#191;', '&iquest;', 'Inverted question mark', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (192, 300, 'C0', 11000000, 'À', '&#192;', '&Agrave;', 'Latin capital letter A with grave', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (193, 301, 'C1', 11000001, 'Á', '&#193;', '&Aacute;', 'Latin capital letter A with acute', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (194, 302, 'C2', 11000010, 'Â', '&#194;', '&Acirc;', 'Latin capital letter A with circumflex', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (195, 303, 'C3', 11000011, 'Ã', '&#195;', '&Atilde;', 'Latin capital letter A with tilde', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (196, 304, 'C4', 11000100, 'Ä', '&#196;', '&Auml;', 'Latin capital letter A with diaeresis', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (197, 305, 'C5', 11000101, 'Å', '&#197;', '&Aring;', 'Latin capital letter A with ring above', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (198, 306, 'C6', 11000110, 'Æ', '&#198;', '&AElig;', 'Latin capital letter AE', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (199, 307, 'C7', 11000111, 'Ç', '&#199;', '&Ccedil;', 'Latin capital letter C with cedilla', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (200, 310, 'C8', 11001000, 'È', '&#200;', '&Egrave;', 'Latin capital letter E with grave', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (201, 311, 'C9', 11001001, 'É', '&#201;', '&Eacute;', 'Latin capital letter E with acute', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (202, 312, 'CA', 11001010, 'Ê', '&#202;', '&Ecirc;', 'Latin capital letter E with circumflex', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (203, 313, 'CB', 11001011, 'Ë', '&#203;', '&Euml;', 'Latin capital letter E with diaeresis', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (204, 314, 'CC', 11001100, 'Ì', '&#204;', '&Igrave;', 'Latin capital letter I with grave', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (205, 315, 'CD', 11001101, 'Í', '&#205;', '&Iacute;', 'Latin capital letter I with acute', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (206, 316, 'CE', 11001110, 'Î', '&#206;', '&Icirc;', 'Latin capital letter I with circumflex', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (207, 317, 'CF', 11001111, 'Ï', '&#207;', '&Iuml;', 'Latin capital letter I with diaeresis', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (208, 320, 'D0', 11010000, 'Ð', '&#208;', '&ETH;', 'Latin capital letter ETH', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (209, 321, 'D1', 11010001, 'Ñ', '&#209;', '&Ntilde;', 'Latin capital letter N with tilde', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (210, 322, 'D2', 11010010, 'Ò', '&#210;', '&Ograve;', 'Latin capital letter O with grave', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (211, 323, 'D3', 11010011, 'Ó', '&#211;', '&Oacute;', 'Latin capital letter O with acute', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (212, 324, 'D4', 11010100, 'Ô', '&#212;', '&Ocirc;', 'Latin capital letter O with circumflex', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (213, 325, 'D5', 11010101, 'Õ', '&#213;', '&Otilde;', 'Latin capital letter O with tilde', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (214, 326, 'D6', 11010110, 'Ö', '&#214;', '&Ouml;', 'Latin capital letter O with diaeresis', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (215, 327, 'D7', 11010111, '×', '&#215;', '&times;', 'Multiplication sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (216, 330, 'D8', 11011000, 'Ø', '&#216;', '&Oslash;', 'Latin capital letter O with slash', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (217, 331, 'D9', 11011001, 'Ù', '&#217;', '&Ugrave;', 'Latin capital letter U with grave', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (218, 332, 'DA', 11011010, 'Ú', '&#218;', '&Uacute;', 'Latin capital letter U with acute', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (219, 333, 'DB', 11011011, 'Û', '&#219;', '&Ucirc;', 'Latin capital letter U with circumflex', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (220, 334, 'DC', 11011100, 'Ü', '&#220;', '&Uuml;', 'Latin capital letter U with diaeresis', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (221, 335, 'DD', 11011101, 'Ý', '&#221;', '&Yacute;', 'Latin capital letter Y with acute', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (222, 336, 'DE', 11011110, 'Þ', '&#222;', '&THORN;', 'Latin capital letter THORN', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (223, 337, 'DF', 11011111, 'ß', '&#223;', '&szlig;', 'Latin small letter sharp s - ess-zed', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (224, 340, 'E0', 11100000, 'à', '&#224;', '&agrave;', 'Latin small letter a with grave', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (225, 341, 'E1', 11100001, 'á', '&#225;', '&aacute;', 'Latin small letter a with acute', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (226, 342, 'E2', 11100010, 'â', '&#226;', '&acirc;', 'Latin small letter a with circumflex', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (227, 343, 'E3', 11100011, 'ã', '&#227;', '&atilde;', 'Latin small letter a with tilde', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (228, 344, 'E4', 11100100, 'ä', '&#228;', '&auml;', 'Latin small letter a with diaeresis', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (229, 345, 'E5', 11100101, 'å', '&#229;', '&aring;', 'Latin small letter a with ring above', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (230, 346, 'E6', 11100110, 'æ', '&#230;', '&aelig;', 'Latin small letter ae', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (231, 347, 'E7', 11100111, 'ç', '&#231;', '&ccedil;', 'Latin small letter c with cedilla', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (232, 350, 'E8', 11101000, 'è', '&#232;', '&egrave;', 'Latin small letter e with grave', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (233, 351, 'E9', 11101001, 'é', '&#233;', '&eacute;', 'Latin small letter e with acute', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (234, 352, 'EA', 11101010, 'ê', '&#234;', '&ecirc;', 'Latin small letter e with circumflex', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (235, 353, 'EB', 11101011, 'ë', '&#235;', '&euml;', 'Latin small letter e with diaeresis', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (236, 354, 'EC', 11101100, 'ì', '&#236;', '&igrave;', 'Latin small letter i with grave', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (237, 355, 'ED', 11101101, 'í', '&#237;', '&iacute;', 'Latin small letter i with acute', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (238, 356, 'EE', 11101110, 'î', '&#238;', '&icirc;', 'Latin small letter i with circumflex', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (239, 357, 'EF', 11101111, 'ï', '&#239;', '&iuml;', 'Latin small letter i with diaeresis', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (240, 360, 'F0', 11110000, 'ð', '&#240;', '&eth;', 'Latin small letter eth', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (241, 361, 'F1', 11110001, 'ñ', '&#241;', '&ntilde;', 'Latin small letter n with tilde', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (242, 362, 'F2', 11110010, 'ò', '&#242;', '&ograve;', 'Latin small letter o with grave', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (243, 363, 'F3', 11110011, 'ó', '&#243;', '&oacute;', 'Latin small letter o with acute', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (244, 364, 'F4', 11110100, 'ô', '&#244;', '&ocirc;', 'Latin small letter o with circumflex', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (245, 365, 'F5', 11110101, 'õ', '&#245;', '&otilde;', 'Latin small letter o with tilde', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (246, 366, 'F6', 11110110, 'ö', '&#246;', '&ouml;', 'Latin small letter o with diaeresis', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (247, 367, 'F7', 11110111, '÷', '&#247;', '&divide;', 'Division sign', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (248, 370, 'F8', 11111000, 'ø', '&#248;', '&oslash;', 'Latin small letter o with slash', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (249, 371, 'F9', 11111001, 'ù', '&#249;', '&ugrave;', 'Latin small letter u with grave', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (250, 372, 'FA', 11111010, 'ú', '&#250;', '&uacute;', 'Latin small letter u with acute', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (251, 373, 'FB', 11111011, 'û', '&#251;', '&ucirc;', 'Latin small letter u with circumflex', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (252, 374, 'FC', 11111100, 'ü', '&#252;', '&uuml;', 'Latin small letter u with diaeresis', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (253, 375, 'FD', 11111101, 'ý', '&#253;', '&yacute;', 'Latin small letter y with acute', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (254, 376, 'FE', 11111110, 'þ', '&#254;', '&thorn;', 'Latin small letter thorn', 'Extended character', '', '')
INSERT INTO dbo.AsciiCode (DecimalCode, OctalCode, HexidecimalCode, BinaryCode, Symbol, HtmlNumber, HtmlName, CodeDescription, CharacterGroup, CaretNotation, CharacterEscapeCode)
	VALUES (255, 377, 'FF', 11111111, 'ÿ', '&#255;', '&yuml;', 'Latin small letter y with diaeresis', 'Extended character', '', '')

UPDATE dbo.AsciiCode
SET Symbol = NULL
WHERE Symbol = ''
UPDATE dbo.AsciiCode
SET HtmlNumber = NULL
WHERE HtmlNumber = ''
UPDATE dbo.AsciiCode
SET HtmlName = NULL
WHERE HtmlName = ''
UPDATE dbo.AsciiCode
SET CodeDescription = NULL
WHERE CodeDescription = ''
UPDATE dbo.AsciiCode
SET CaretNotation = NULL
WHERE CaretNotation = ''
UPDATE dbo.AsciiCode
SET CharacterEscapeCode = NULL
WHERE CharacterEscapeCode = ''